# Generated by Django 5.0.2 on 2024-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logoimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('toplogo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='myproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to='project_image')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_short', models.CharField(max_length=500)),
                ('title_long', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='slider')),
                ('pdf', models.FileField(upload_to='slider')),
            ],
        ),
    ]
