# Generated by Django 5.0.2 on 2024-04-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to='project_image')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.myproject')),
            ],
        ),
    ]
