# Generated by Django 5.0.2 on 2024-04-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_projectdetails_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='title',
            new_name='post_title',
        ),
    ]
