# Generated by Django 5.0.2 on 2024-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_title_projectdetails_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_image',
            field=models.ImageField(upload_to='projectdetails'),
        ),
    ]
