# Generated by Django 5.0.2 on 2024-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_projectdetails_add_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectdetails',
        ),
    ]
