# Generated by Django 5.0.2 on 2024-05-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_delete_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoimg',
            name='urlLink',
            field=models.URLField(null=True),
        ),
    ]
