# Generated by Django 5.0.2 on 2024-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_logoimg_urllink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoimg',
            name='urlLink',
        ),
        migrations.AddField(
            model_name='myproject',
            name='urlLink',
            field=models.URLField(null=True),
        ),
    ]
