# Generated by Django 5.0.2 on 2024-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_logoimg_urllink_myproject_urllink'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
