# Generated by Django 5.0.2 on 2024-05-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_projectdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='urlLink',
        ),
    ]
