# Generated by Django 5.0.2 on 2024-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to='slider'),
            preserve_default=False,
        ),
    ]
