# Generated by Django 5.0.2 on 2024-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
