# Generated by Django 5.0.2 on 2024-05-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_projectdetails_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='url',
        ),
    ]
