# Generated by Django 5.0.2 on 2024-05-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_projectdetails_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='Url_add',
            field=models.URLField(blank=True, null=True),
        ),
    ]
