# Generated by Django 5.0.2 on 2024-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hear_me',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
