# Generated by Django 5.0.2 on 2024-05-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_contact_add_date_hear_me_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='description_title',
        ),
    ]
