# Generated by Django 5.0.2 on 2024-05-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_myproject_description_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='description_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
